### ISSUE TITLE
Can't get shardman work on vanilla PG 11

### ISSUE THREAD

**Issue by ratanasov1** [postgrespro/pg_shardman#6]
[Solved] The reason was the examples did not include the shardman schema and I was calling pg_pathman create_hash_partitions

I installed shardman on vanilla PG11. To do that I had to disable
logical_replication_2pc = ...
track_global_snapshots = ...
global_snapshot_defer_time = ...

I ran the shardman_init.sh and all seemed to run fine. I logged to the lord, added 2 workers, created the horns table, then sharded it according to the example. It complained about reduncancy, so I removed it.

I insert 1000 tuples into horn table. Nothing seems to go to any of the workers. It all stays on the lord.

I noticed that the shardman.nodes table has the nodes, but the shardman.partitions is empty.

How can I get shardman work on vanilla PG11. I don't need cross-node transactions.

**Comment by arssher** [comment]
Hi,

Thanks for the update, I've added schema to the example. But generally, usage of logical replication in this project doesn't seem as a right approach, and pg_pathman should be replaced by native partitioning developed by the community, so it is unlikely this project is going to be developed in its current form anymore.
